### ISSUE TITLE
Node death notification events not delivered with PMIX v3.0.2

### ISSUE THREAD

**Issue by frostedcmos** [pmix/prrte#120]
## Background information
PMIX = v3.0.2
PRRTE = 7a348382e9291b1cc1fab4117f16136fcb0a8e4b

### Please describe the system on which you are running
CentOS Linux release 7.2.1511 (Core)
Local network over ofi+sockets

-----------------------------

## Details of the problem

As we attempt to switch from orterun to prun (along with updating to more recent pmix compatible with prrte), we encounter an issue of node death notifications not being delivered.

When multiple servers/apps are started in a process group together, and one of them dies/terminates, previously (using orterun and older pmix) we would receive a pmix notification about the death of the set member. We are no longer seeing the same behavior with switch to v3.0.2 of pmix and using prun.

Details:
2 sample servers are started on the same node using prun to start as part of the set of size=2.
1 server kills self, the other one awaits for pmix notification of the death of the other node.

Sample test used by our project which uses PMIX apis for registration:
https://github.com/daos-stack/cart/blob/master/src/test/test_pmix.c

Prior to running the test we start prte as:
prte  --daemonize -system-server -H "our_hostname:*"

The actual test is ran as:
prun --continuous -N 2  -x D_LOG_MASK=INFO  tests/test_pmix

The test currently times out after not seeing notification of a dead member.

**Comment by rhc54** [comment]
This should now be fixed - please reopen this issue if you continue to have a problem.
