### ISSUE TITLE
non friendly error message when a job cannot be spawned

### ISSUE THREAD

**Issue by ggouaillardet** [pmix/prrte#171]
With latest `prte` and `pmix` from their `master` branches.

I incorrectly passed the `-c` flag to `pcc` and hence generated an object file when I really meant to generate a binary. Then I tried to `prun` it and ended up with a non understandable error message

```
$ ~/local/prrte/bin/pcc -c -g -O0 -o hello hello.c 
$ ~/local/prrte/bin/prun -n 1 ./hello
[c7:31224] Job failed to spawn: ERROR STRING NOT FOUND

```

The bash error is a `Permission denied` (since the executable bit is not set on an object), and I would expect a similar error is reported by `prun`.

**Comment by rhc54** [comment]
Fixed this one with #177
