### ISSUE TITLE
Problem in IOF subsystem

### ISSUE THREAD

**Issue by rhc54** [pmix/prrte#173]
@ggouaillardet 

I've tracked down the instability problem to an issue in the IOF, specifically when forwarding IO to the prun tool. At some point, we wind up hitting a situation where the write fails (reason unclear) and then the msg attempts to be released, only to segfault due to a bad pointer:
```shell
Execution 20
[Ralphs-iMac-2.local:18679] SENDONEWAY server/pmix_server.c:1677:2
[Ralphs-iMac-2.local:18679] pmix_ptl_base: send_msg: write failed: Invalid argument (22) [sd = 14]
prte(18679,0x70000c640000) malloc: *** error for object 0x7fc5ed00f348: pointer being freed was not allocated
prte(18679,0x70000c640000) malloc: *** set a breakpoint in malloc_error_break to debug
[Ralphs-iMac-2.local:19175] PMIX ERROR: UNPACK-PAST-END in file event/pmix_event_registration.c at line 99
```
The last error comes from prun because it received only a partial payload.

It is unclear to me why the msg object is getting trashed. Here is what I see from gdb of the resulting prte core file:
```shell
(gdb) thread apply all where

Thread 5 (core thread 4):
#0  0x00007fff7c6655aa in select$DARWIN_EXTSN ()
#1  0x00000001029432ab in listen_thread (obj=0x102951850) at oob_tcp_listener.c:705
#2  0x00007fff7c718305 in _pthread_body ()
#3  0x00007fff7c71b26f in _pthread_start ()
#4  0x00007fff7c717415 in thread_start ()

Thread 4 (core thread 3):
#0  0x00007fff7c664716 in kevent ()
#1  0x00000001005a70c6 in kq_dispatch (base=0x7fc5eaf0c380, tv=<value temporarily unavailable, due to optimizations>) at kqueue.c:302
#2  0x00007000000f421a in ?? ()

Thread 3 (core thread 2):
#0  0x00007fff7c6655aa in select$DARWIN_EXTSN ()
#1  0x00000001004f2713 in listen_thread (obj=0x0) at base/ptl_base_listener.c:214
#2  0x00007fff7c718305 in _pthread_body ()
#3  0x00007fff7c71b26f in _pthread_start ()
#4  0x00007fff7c717415 in thread_start ()

Thread 2 (core thread 1):
#0  0x00007fff7c66423e in __pthread_kill ()
#1  0x00007fff7c71ac1c in pthread_kill ()
#2  0x00007fff7c5cd268 in __abort ()
#3  0x00007fff7c5cd1d8 in abort ()
#4  0x00007fff7c6dc6e2 in malloc_vreport ()
#5  0x00007fff7c6dc4a3 in malloc_report ()
#6  0x00000001004efd63 in pmix_ptl_base_send_handler (sd=14, flags=4, cbdata=0x7fc5ed00f1c0) at base/ptl_base_sendrecv.c:438
#7  0x000000010059e0e8 in event_process_active_single_queue (base=0x7fc5eaf005b0, activeq=0x7fc5eaf00880, max_to_process=2147483647, endtime=0x0) at event.c:1580
Previous frame inner to this frame (gdb could not unwind past this frame)

Thread 1 (core thread 0):
#0  0x00007fff7c6617de in __psynch_cvwait ()
#1  0x00007fff7c71b593 in _pthread_cond_wait ()
#2  0x00000001002af994 in orte_state_base_track_procs (fd=-1, argc=4, cbdata=0x7fc5ed0333b0) at base/state_base_fns.c:732
#3  0x000000010059de75 in event_process_active_single_queue (base=0x7fc5eac14860, activeq=0x7fc5eac14bf0, max_to_process=2147483647, endtime=0x0) at event.c:1646
Previous frame inner to this frame (gdb could not unwind past this frame)
(gdb) thread 2\

[Switching to thread 2 (core thread 1)]
0x00007fff7c66423e in __pthread_kill ()
(gdb) up
#1  0x00007fff7c71ac1c in pthread_kill ()
(gdb) up
#2  0x00007fff7c5cd268 in __abort ()
(gdb) up
#3  0x00007fff7c5cd1d8 in abort ()
(gdb) up
#4  0x00007fff7c6dc6e2 in malloc_vreport ()
(gdb) up
#5  0x00007fff7c6dc4a3 in malloc_report ()
(gdb) up
#6  0x00000001004efd63 in pmix_ptl_base_send_handler (sd=14, flags=4, cbdata=0x7fc5ed00f1c0) at base/ptl_base_sendrecv.c:438
438	            PMIX_RELEASE(msg);
(gdb) print msg
$1 = (pmix_ptl_send_t *) 0x7fc5ed00f348
(gdb) print *msg
$2 = {
  super = {
    super = {
      obj_magic_id = 0, 
      obj_class = 0x100526940, 
      obj_reference_count = 0, 
      cls_init_file_name = 0x1005071e7 "base/ptl_base_sendrecv.c", 
      cls_init_lineno = 438
    }, 
    pmix_list_next = 0x0, 
    pmix_list_prev = 0x0, 
    item_free = 1, 
    pmix_list_item_refcount = 0, 
    pmix_list_item_belong_to = 0x0
  }, 
  ev = {
    ev_evcallback = {
      evcb_active_next = {
        tqe_next = 0xd8, 
        tqe_prev = 0x7fc5ed00f348
      }, 
      evcb_flags = 0, 
      evcb_pri = 0 '\0', 
      evcb_closure = 0 '\0', 
      evcb_cb_union = {
        evcb_callback = 0x7fc500000000, 
        evcb_selfcb = 0x7fc500000000, 
        evcb_evfinalize = 0x7fc500000000, 
        evcb_cbfinalize = 0x7fc500000000
      }, 
      evcb_arg = 0x14000003e8
    }, 
    ev_timeout_pos = {
      ev_next_with_common_timeout = {
        tqe_next = 0xdeafbeeddeafbeed, 
        tqe_prev = 0x100526980
      }, 
      min_heap_idx = -558907667
    }, 
    ev_fd = 1, 
    ev_base = 0x1004f84ae, 
    ev_ = {
      ev_io = {
        ev_io_next = {
          le_next = 0x7fc5000000ba, 
          le_prev = 0xdeafbeeddeafbeed
        }, 
        ev_timeout = {
          tv_sec = 4300368192, 
          tv_usec = 1
        }
      }, 
      ev_signal = {
        ev_signal_next = {
          le_next = 0x7fc5000000ba, 
          le_prev = 0xdeafbeeddeafbeed
        }, 
        ev_ncalls = 26944, 
        ev_pncalls = 0x7fc500000001
      }
    }, 
    ev_events = 28067, 
    ev_res = 79, 
    ev_timeout = {
      tv_sec = 140484085284953, 
      tv_usec = -318704672
    }
  }, 
  hdr = {
    pindex = -318704672, 
    tag = 32709, 
    nbytes = 4294967297
  }, 
  data = 0x7fc5ed00f3b8, 
  hdr_sent = false, 
  sdptr = 0xdeafbeeddeafbeed <Address 0xdeafbeeddeafbeed out of bounds>, 
  sdbytes = 4300368256
}
(gdb) print msg->data
$3 = (pmix_buffer_t *) 0x7fc5ed00f3b8
(gdb) print *msg->data
$4 = {
  parent = {
    obj_magic_id = 16046253926196952813, 
    obj_class = 0x100526980, 
    obj_reference_count = 1, 
    cls_init_file_name = 0x1004f84ae "include/pmix_globals.c", 
    cls_init_lineno = 186
  }, 
  type = 237 '?', 
  base_ptr = 0x100526940 "?mO", 
  pack_ptr = 0x7fc500000001 <Address 0x7fc500000001 out of bounds>, 
  unpack_ptr = 0x1004f6da3 "class/pmix_list.c", 
  bytes_allocated = 140484085284953, 
  bytes_used = 140488061547488
}
```
Can you take a look when you return? I'm guessing that we were only able to do a partial send, and that messed up the pointer to msg such that the subsequent attempt to complete the send errors out. Since the msg pointer has been messed up, we hit the "malloc free" error and abort.

**Comment by ggouaillardet** [comment]
@rhc54 sure, I'll take a crack at it !

how can you reproduce this issue ?
does a simple non PMIx program that writes a lot to stdout can do the trick ?

**Comment by rhc54** [comment]
You can find my "cycle.sh" here: https://github.com/pmix/pmix-tests/blob/master/prrte/cycle.sh

**Comment by rhc54** [comment]
I think I've thought through the issue, though I haven't attempted a fix. I believe the problem is a race condition between PRRTE sending a job-terminated notice to prun and the IOF sending the output to prun. If the job-terminated notification gets delivered first, then prun will exit - yet the IOF doeesn't know that has happened and still attempts to write the apps output down the (now defunct) socket.

The issue is that prun is not a child of PRRTE - it's just a connected tool. We need to ensure that any IOF collected from the associated app gets sent to prun _before_ we send the termination notification. We then need to ensure that prun outputs any received IO prior to actually terminating - guess we need an "IOF flush" somewhere in prun's finalization routine.

HTH

**Comment by rhc54** [comment]
@ggouaillardet I spent the day working on this and found that my above premise was incorrect - this had nothing really to do with the IOF. The problem appears to be in either the notification or the messaging system of the client.

What I found was that we were caching notifications for a long period of time, as you previously noted. However, since PRRTE wasn't providing set targets for those job-termination notices, every prun would get a flood of notices about prior jobs when it connected to the server. The client event system would filter those so that prun itself never saw them, but once you built up a lot of them, prun would start to hang under the flood.

Adding the IOF into the mix seemed to make it happen faster, though I couldn't solidly confirm that impression. I'm inclined to believe it is solidly in the event system because I was able to fix the problem by revamping solely the event system. However, the revamp also eliminated the message flood, and so I might have solved only the symptom. We need to stress the server-to-client message system to be sure.

My fixes are in two PRs, one for PMIx itself and the other for PRRTE:
https://github.com/pmix/pmix/pull/1003
https://github.com/pmix/prrte/pull/175

With those fixes, I am able to run my cycle.sh test essentially forever (well, I tested 10k iterations without a problem, so that's forever to me!).

Would you have a chance to check out the messaging system? I'd like to ensure my fixes aren't just masking the root cause of the problem.

**Comment by rhc54** [comment]
Looks like this is fixed
