### ISSUE TITLE
Occasional error messages from client at program start

### ISSUE THREAD

**Issue by tonycurtis** [pmix/prrte#221]
Thank you for taking the time to submit an issue!

### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

PMIx server: github master @ 315681dacd2bb2f1a9817ff0e37e2ed4ca073cda

PMIx client: github master @ ef2575f3ac21a3261da16d827fe2efd27b46151c

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

git-clone

### Please describe the system on which you are running

* Operating system/version: CentOS 7
* Computer hardware: x86_64
* Network type: IB

-----------------------------

## Details of the problem

At program start, I _occasionally_ see these messages from the client code

```shell
[cn090:05314] [[43133,0],1] ORTE_ERROR_LOG: Not found in file ../../prrte-git/orte/util/nidmap.c at line 761
[cn090:05314] [[43133,0],1] ORTE_ERROR_LOG: Not found in file ../../prrte-git/orte/orted/orted_comm.c at line 270
```

the program still continues to run fine though.

**Comment by rhc54** [comment]
Odd - does your system have any nodes with a different topology - e.g., different number of sockets, number of cores, ...?

**Comment by tonycurtis** [comment]
> On Mar 25, 2019, at 1:18 PM, Ralph Castain <notifications@github.com> wrote:
> 
> Odd - does your system have any nodes with a different topology - e.g., different number of sockets, number of cores, …?
> 

Yes, but jobs will use all the same kind of node.  Also, the messages are currently showing up in 2nd and later runs, not in the first.  Completely separate PRTE spawned per run.

E.g.

cn086[1](~/shmem/openshmem-examples/C) oshrun ./a.out
oshrun:prrte: found "prun"
oshrun:prrte: check matching "prte"
oshrun:prrte: found "prte"
oshrun:prrte: starting up
oshrun:prrte: pid 25126 says "DVM ready"
oshrun:launch: "prun ./a.out"
oshrun:launch: application in process 25134
oshrun:----------------------------------------------------------------------
cn086: Hello from PE    0 of    4
cn086: Hello from PE    1 of    4
cn094: Hello from PE    2 of    4
cn094: Hello from PE    3 of    4
oshrun:prrte: process 25126 shut down
cn086[1](~/shmem/openshmem-examples/C) oshrun ./a.out
oshrun:prrte: found "prun"
oshrun:prrte: check matching "prte"
oshrun:prrte: found "prte"
oshrun:prrte: starting up
oshrun:prrte: pid 25164 says "DVM ready"
oshrun:launch: "prun ./a.out"
oshrun:launch: application in process 25169
oshrun:----------------------------------------------------------------------
[cn094:06270] [[17285,0],1] ORTE_ERROR_LOG: Not found in file ../../prrte-git/orte/util/nidmap.c at line 761
[cn094:06270] [[17285,0],1] ORTE_ERROR_LOG: Not found in file ../../prrte-git/orte/orted/orted_comm.c at line 270
cn086: Hello from PE    0 of    4
cn086: Hello from PE    1 of    4
cn094: Hello from PE    2 of    4
cn094: Hello from PE    3 of    4
oshrun:prrte: process 25164 shut down
cn086[1](~/shmem/openshmem-examples/C) oshrun ./a.out
oshrun:prrte: found "prun"
oshrun:prrte: check matching "prte"
oshrun:prrte: found "prte"
oshrun:prrte: starting up
oshrun:prrte: pid 25188 says "DVM ready"
oshrun:launch: "prun ./a.out"
oshrun:launch: application in process 25193
oshrun:----------------------------------------------------------------------
[cn094:06288] [[17325,0],1] ORTE_ERROR_LOG: Not found in file ../../prrte-git/orte/util/nidmap.c at line 761
[cn094:06288] [[17325,0],1] ORTE_ERROR_LOG: Not found in file ../../prrte-git/orte/orted/orted_comm.c at line 270
cn086: Hello from PE    0 of    4
cn086: Hello from PE    1 of    4
cn094: Hello from PE    2 of    4
cn094: Hello from PE    3 of    4
oshrun:prrte: process 25188 shut down
cn086[1](~/shmem/openshmem-examples/C) oshrun ./a.out
oshrun:prrte: found "prun"
oshrun:prrte: check matching "prte"
oshrun:prrte: found "prte"
oshrun:prrte: starting up
oshrun:prrte: pid 25212 says "DVM ready"
oshrun:launch: "prun ./a.out"
oshrun:launch: application in process 25217
oshrun:----------------------------------------------------------------------
[cn094:06308] [[17333,0],1] ORTE_ERROR_LOG: Not found in file ../../prrte-git/orte/util/nidmap.c at line 761
[cn094:06308] [[17333,0],1] ORTE_ERROR_LOG: Not found in file ../../prrte-git/orte/orted/orted_comm.c at line 270
cn086: Hello from PE    0 of    4
cn086: Hello from PE    1 of    4
cn094: Hello from PE    2 of    4
cn094: Hello from PE    3 of    4
oshrun:prrte: process 25212 shut down


“lscpu” shows both nodes with identical config.

tony

**Comment by tonycurtis** [comment]
Actually, now just running `prte` on its own gives the error messages:

```sh
DVM ready
[cn094:07572] [[18882,0],1] ORTE_ERROR_LOG: Not found in file ../../prrte-git/orte/util/nidmap.c at line 761
                            [cn094:07572] [[18882,0],1] ORTE_ERROR_LOG: Not found in file ../../prrte-git/orte/orted/orted_comm.c at line 270
```

**Comment by tonycurtis** [comment]
Also getting the following from `prte` at times:

```
[login2:185470] PMIX ERROR: BAD-PARAM in file ../../../../pmix-git/src/mca/bfrops/base/bfrop_base_pack.c at line 48
[login2:185470] PMIX ERROR: BAD-PARAM in file ../../pmix-git/src/server/pmix_server.c at line 2258
```

**Comment by tonycurtis** [comment]
No error messages at all (so far) in jobs that occupy the whole node.  Only get the messages when I ask for < the available number of cores, e.g. 2 nodes but only request 2 cores per node.

**Comment by rhc54** [comment]
Ahhhh...thanks! That helps me to narrow it down.

**Comment by tonycurtis** [comment]
And the error messages always come from `prte` on the "other" node (2 node job)
