### ISSUE TITLE
Exchanging data with PMIx_Publish/Lookup does not scale well

### ISSUE THREAD

**Issue by lyu** [pmix/prrte#225]
### What version of the PMIx Reference Server are you using?

github master @ 716be58 (so that it compiles with PMIx 3.1.2)

#### What version of PMIx are you using?

PMIx 3.1.2 (w/ external hwloc 2.0.3)

### Please describe the system on which you are running

* Operating system/version: `CentOS Linux release 7.5.1804 x86_64`
* Computer hardware: `Xeon E5-2690 v3`
* Network type:
```
Ethernet controller: Intel Corporation Ethernet Controller 10-Gigabit X540-AT2 (rev 01)

Infiniband controller: Mellanox Technologies MT27600 [Connect-IB]
```

-----------------------------

## Details of the problem

Hello, we are the maintainers of the OpenSHMEM implementation OSSS-UCX, which uses PMIx to exchange UCX parameters during its start-up.

Details: [https://github.com/openshmem-org/osss-ucx/blob/master/src/shmemc/ucx/pmix_client.c](https://github.com/openshmem-org/osss-ucx/blob/master/src/shmemc/ucx/pmix_client.c)

Initially we use `PMIx_Publish` and `PMIx_Lookup` to do it, but this approach scales poorly on several HPC clusters that we have tested it on. For a simple hello world program that does nothing other than calling `shmem_init()` and `shmem_finalize()`, it takes OSSS-UCX about 120 seconds to do the job on 192 PEs. Below is a trimmed output of Linux kernel's `perf` profiler.

```
|--90.89%--orte_rml_base_process_msg
|          |          
|           --90.44%--orte_data_server
|                     |          
|                     |--82.08%--orte_util_print_name_args
|                     |          |          
|                     |          |--32.02%--__snprintf
|                     |          |          |          
|                     |          |           --31.64%--_IO_vsnprintf
|                     |          |                     |          
|                     |          |                     |--27.75%--vfprintf
|                     |          |                     |          
|                     |          |                     |--1.62%--_IO_str_init_static_internal
|                     |          |                     |          
|                     |          |                      --1.52%--_IO_no_init
|                     |          |          
|                     |          |--30.60%--orte_util_print_jobids
|                     |          |          |          
|                     |          |          |--29.22%--__snprintf
|                     |          |          |          |          
|                     |          |          |           --28.81%--_IO_vsnprintf
|                     |          |          |                     |          
|                     |          |          |                     |--25.23%--vfprintf
|                     |          |          |                     |          
|                     |          |          |                     |--1.72%--_IO_str_init_static_internal
|                     |          |          |                     |          
|                     |          |          |                      --1.03%--_IO_no_init
|                     |          |          |          
|                     |          |           --0.60%--get_print_name_buffer
|                     |          |          
|                     |          |--17.00%--orte_util_print_vpids
|                     |          |          |          
|                     |          |          |--15.09%--__snprintf
|                     |          |          |          |          
|                     |          |          |           --14.56%--_IO_vsnprintf
|                     |          |          |                     |          
|                     |          |          |                     |--10.41%--vfprintf
|                     |          |          |                     |          
|                     |          |          |                     |--1.77%--_IO_no_init
|                     |          |          |                     |          
|                     |          |          |                      --1.52%--_IO_str_init_static_internal
|                     |          |          |          
|                     |          |           --0.98%--get_print_name_buffer
|                     |          |                     |          
|                     |          |                      --0.76%--pthread_getspecific
|                     |          |          
|                     |           --1.25%--get_print_name_buffer
|                     |                     |          
|                     |                      --0.80%--pthread_getspecific
|                     |          
|                     |--3.78%--__strncmp_sse42
|                     |          
|                     |--0.80%--pthread_mutex_unlock
|                     |          
|                      --0.67%--pthread_mutex_lock
```

Apparently, the function `orte_data_server` was called many many times and 90% of the total run time was spend on it.

Looking closer, the function `orte_util_print_name_args` (`ORTE_NAME_PRINT`) is the most expensive part, as it always formats the log strings even if no log gets printed.

I forked prrte and removed all the lines in `orte_data_server` that contains `ORTE_NAME_PRINT`, and this reduced the total run time of the hello world program to around 20 seconds (`orte_data_server` is still being called many many times).

In the development branch of OSSS-UCX we have switched to `PMIx_Get/Put/Commit` and now it only takes about 10 seconds to run the hello world program on 192 PEs without needing to remove the string formatting macro.

New version: [https://bitbucket.org/wenblu/osss-ucx/src/master/src/shmemc/ucx/pmix_client.c](https://bitbucket.org/wenblu/osss-ucx/src/master/src/shmemc/ucx/pmix_client.c)

@tonycurtis

**Comment by ggouaillardet** [comment]
Did you configure `prrte` with `--enable-debug` ? If you do not, some calls to `ORTE_NAME_PRINT` will be #ifdef’ed out and performance should be much higher.

**Comment by lyu** [comment]
@ggouaillardet This is my prrte configuration:

```
./configure --prefix=$INSTALLPATH --with-hwloc=$INSTALLPATH --with-pmix=$INSTALLPATH --with-libevent=$HOME/.local --without-slurm --with-tm=/cm/shared/apps/torque/6.1.1
```

I tried again and specified `--disable-debug`, same behavior.

**Comment by rhc54** [comment]
Setting aside the debug question - the use of publish/lookup to exchange endpoint data is never going to work well as it was not intended for that purpose. If you read the standard, you will see that the exchange of data during wireup is done with the code path you eventually adopted - put/commit/fence/get. This code path is done as a collective operation and thus can scale.

Publish/lookup is intended for things like the rendezvous between two unrelated jobs where one process from each job takes responsibility for posting and retrieving the information about the other job, and then disseminating it to its peers. It is designed not to scale for the simple reason that it isn't a collective operation - thus, you can not take advantage of any of the scalable operations used in the other code path.

At some point in the near future, you will not need to put/commit any data. All endpoint information will be pre-computed and provided at startup. Thus, there will be no time required to start the job beyond just the time it takes to fork/exec the processes.

**Comment by lyu** [comment]
@rhc54 Thanks for the explanation! Closing.

**Comment by ggouaillardet** [comment]
@lyu your report contains a valid point regarding the (mostly unnecessary) cost of `ORTE_NAME_PRINT()`

could you please manually download and apply the patch at https://github.com/pmix/prrte/pull/226.patch ?
long story short, most `ORTE_NAME_PRINT()` calls will be avoided.

**Comment by lyu** [comment]
@ggouaillardet This patch works as good as manually removing the `opal_output_verbose` function calls!
