### ISSUE TITLE
pcc is not using the right pmix.h

### ISSUE THREAD

**Issue by dong0321** [pmix/prrte#54]
### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)
prrte version: master @ 1aec6c478c9c83658b1d96a0d219c6e254e11221
### Is the reference server using its internal version of PMIx, or an external one?
external 
##### If external, what version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)
pmix : master @ be15631db82cf9b3fd5078f1336812de0b500838

##### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
git clone

## Details of the problem

When i use pcc to compile the ompi/examples, it not using the external pmix.h. 
with $pcc --show-me 
the -I/external_pmix_install_path/include is missing.

**Comment by rhc54** [comment]
This should be fixed now as PMIx is always external - please re-open if you continue to see the problem.
