### ISSUE TITLE
prun: propagate app exit code to caller?

### ISSUE THREAD

**Issue by tonycurtis** [pmix/prrte#92]
Thank you for taking the time to submit an issue!

## Background information

Trying to trap a exit codes from an app launched via prun (and prte). 

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

git master @093174a070fbcf76bb00df78c7d4f4b0ef3c4da8 

### Is the reference server using its internal version of PMIx, or an external one?

External

##### If external, what version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

git master @35ae8a0320c32023fb1a2ab087352d07e888bfc9

##### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

source

### Please describe the system on which you are running

* Operating system/version: CentOS 7
* Computer hardware: x86_64
* Network type: IBV

-----------------------------

## Details of the problem

If the app exit(1)s or equivalent, can I get this back from prun?  prun always seems to exit(0)

**Comment by rhc54** [comment]
Could you please give the referenced PR a try and see if it works for you?

**Comment by tonycurtis** [comment]
It's still returning 0 no matter what the app does.  Looks like it's actually saying "I started the app OK".

**Comment by rhc54** [comment]
Think I chased it down - can you try again?

**Comment by tonycurtis** [comment]
Thanks.  Almost, but not quite :)  If I exit with some +ve value, I do get that value back, but exit(0) leads to prun exiting with status "1".

**Comment by rhc54** [comment]
Grrr...ok, try this one (had wrong default value)

**Comment by tonycurtis** [comment]
Looks like that might be it.  Thanks!  But will test a bit more.

**Comment by rhc54** [comment]
Please reopen (or open a new one) if you find a continuing problem

**Comment by tonycurtis** [comment]
Unwanted behaviour has reappeared.  Exit status from prun is always "1" (where tested) when end-user app does "exit(anything)".

**Comment by rhc54** [comment]
Rats - okay, will fix. Also need to take that fix upstream so we don't keep getting overwritten on sync.

**Comment by rhc54** [comment]
Odd - I'm not replicating this. Can you perhaps check to ensure that you are at the current head? If so, then is there anything about your configure or execution that is unusual (e.g., parameters)?

**Comment by tonycurtis** [comment]
(In real code, PMIx is master @ 58b2593abdfd8959d1eba0b4fd56758b9bca3afa)

PRRTE is master @ fa56e0ba8798e5ff38bb3539c5b06a9b60b9b164

MWE:

```C
int main() { return 23; }
```
running bare:
```shell
$ ./a.out; echo $?
23
```
running through prun/prte:
```shell
$ prte ...
DVM ready


$ prun -n 1 ./a.out; echo $?
1
```

**Comment by rhc54** [comment]
I'm not seeing it - using your provided test case:
```shell
$ prun -n 1 ./foo
$ echo $?
23
```
Our hashes look the same, so I'm confused. Can you check to ensure that you are getting the prte and prun you expected? Also, note that you had to rerun autogen/configure when updating due to a removed component in PRRTE plus configure updates.

**Comment by tonycurtis** [comment]
Always do autogen each install.  Am rm-rf'ing source and installed directories, re-cloning from github in case of bit-rot.

**Comment by tonycurtis** [comment]
OK, re-clone anew, git HEAD is same hash: autogen, configure, make install, still seeing exit = 1.  Correct (only) prte/prun are first on PATH.

**Comment by rhc54** [comment]
Huh - I re-cloned and was finally able to replicate it. Will have to see what is perhaps lingering on my local repo.

**Comment by rhc54** [comment]
Okay, issue was somehow something to do with the branch of PMIx master I'm using. Once that branch passes CI, I'll commit it to PMIx master - should do the trick.

**Comment by rhc54** [comment]
You might try refreshing pmix master checkout now and see if it works. I'm rebuilding myself just to be sure

**Comment by tonycurtis** [comment]
Looks good, thanks!
